"use client";

import jsPDF from "jspdf";

// ── Clipboard helpers ──

export async function copyToClipboard(text: string): Promise<boolean> {
  try {
    await navigator.clipboard.writeText(text);
    return true;
  } catch {
    return false;
  }
}

// ── PDF helpers ──

interface PDFSection {
  heading?: string;
  subheading?: string;
  body?: string;
  spacerAfter?: number;
}

export function exportToPDF(
  title: string,
  subtitle: string,
  sections: PDFSection[],
  filename: string
) {
  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 18;
  const contentWidth = pageWidth - margin * 2;
  let y = margin;

  const checkPageBreak = (needed: number) => {
    const pageHeight = doc.internal.pageSize.getHeight();
    if (y + needed > pageHeight - margin) {
      doc.addPage();
      y = margin;
    }
  };

  // Header bar
  doc.setFillColor(26, 26, 26); // #1A1A1A
  doc.rect(0, 0, pageWidth, 28, "F");
  doc.setFontSize(16);
  doc.setTextColor(245, 255, 128); // #F5FF80
  doc.setFont("helvetica", "bold");
  doc.text("Tiger Track", margin, 12);
  doc.setFontSize(8);
  doc.setFont("helvetica", "normal");
  doc.text("Job Leveling by Tiger Data", margin, 18);

  // Title
  y = 38;
  doc.setFontSize(14);
  doc.setTextColor(26, 26, 26);
  doc.setFont("helvetica", "bold");
  doc.text(title, margin, y);
  y += 6;

  if (subtitle) {
    doc.setFontSize(9);
    doc.setTextColor(100, 100, 100);
    doc.setFont("helvetica", "normal");
    doc.text(subtitle, margin, y);
    y += 8;
  }

  // Divider
  doc.setDrawColor(245, 255, 128);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageWidth - margin, y);
  y += 8;

  // Sections
  for (const section of sections) {
    if (section.heading) {
      checkPageBreak(14);
      doc.setFontSize(11);
      doc.setTextColor(26, 26, 26);
      doc.setFont("helvetica", "bold");
      doc.text(section.heading, margin, y);
      y += 6;
    }

    if (section.subheading) {
      checkPageBreak(10);
      doc.setFontSize(9);
      doc.setTextColor(255, 91, 41); // #FF5B29
      doc.setFont("helvetica", "bold");
      doc.text(section.subheading, margin, y);
      y += 5;
    }

    if (section.body) {
      checkPageBreak(10);
      doc.setFontSize(9);
      doc.setTextColor(60, 60, 60);
      doc.setFont("helvetica", "normal");
      const lines = doc.splitTextToSize(section.body, contentWidth);
      for (const line of lines) {
        checkPageBreak(5);
        doc.text(line, margin, y);
        y += 4.2;
      }
      y += 2;
    }

    if (section.spacerAfter) {
      y += section.spacerAfter;
    }
  }

  // Footer
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFontSize(7);
    doc.setTextColor(150, 150, 150);
    doc.setFont("helvetica", "normal");
    doc.text(
      `Generated by Tiger Track | ${new Date().toLocaleDateString()} | Page ${i} of ${pageCount}`,
      margin,
      pageHeight - 8
    );
  }

  doc.save(filename);
}
